export const products = [
    {
        id:1,
        name: "Salta3 Burger",
        category: "SpongeBob",
        image:"assets/images/krabby-patty.jpg",
        description: "The famous burger at Qa' al-Hamour",
        price:50,
    },

    {
    id: 2,
    name: "Jellyfish fishing net",
    category: "SpongeBob",
    image: "assets/images/jellyfish-net.jpg",
    description: "SpongeBob's favorite tool for the weekend",
    price: 60,
    },

    {
    id: 3,
    name: "Spatula",
    category: "SpongeBob",
    image: "assets/images/Spatula.jpg",
    description: "The golden spatula for perfect burger flipping",
    price: 80,
    },

      {
        id:4,
        name: "SpongeBed",
        category: "SpongeBob",
        image:"assets/images/SpongeBed.jpg",
        description: "A cozy bed ",
        price:500
    },

    {
    id: 5,
    name: "Chef Hat",
    category: "SpongeBob",
    image: "assets/images/ChefHat.jpg",
    description: "Official hat for the Krusty Krab fry cook",
    price: 20,
    },

    {
    id: 6,
    name: "Kelp Shake",
    category: "SpongeBob",
    image: "assets/images/KelpShake.jpg",
    description: "The famous green drink",
    price: 8,
    },

    {
        id:7,
        name: "Bubble blower",
        category: "Patrick",
        image: "assets/images/Bubbleblower.jpg",
        description: "A simple tool for making bubbles",
        price: 30,
    },

    {
        id:8,
        name: "Alarm Clock",
        category: "Patrick",
        image: "assets/images/alarm.jpg",
        description: "A patrick, traditional alarm clock—though he never uses it to wake up!",
        price: 35,
    },

    {
        id:9,
        name: "Patrick's Shorts",
        category: "Patrick",
        image: "assets/images/PatrickShorts.jpg",
        description: "Comfortable purple shorts with green flowers",
        price: 50,
    },

      {
        id:10,
        name: "Rock House",
        category: "Patrick",
        image:"assets/images/RockHouse.jpg",
        description: "The most stylish rock in Bikini Bottom",
        price:500,
    },

    {
    id: 11,
    name: "Sea Star Sunscreen",
    category: "Patrick",
    image: "assets/images/sunscreen.jpg",
    description: "Protection for a star's skin",
    price: 12,
    },

    {
    id: 12,
    name: "Ice Cream",
    category: "Patrick",
    image: "assets/images/Ice Cream.jpg",
    description: "A melting delight on a hot day",
    price: 10,
    },
    {
        id:13,
        name: "Cash safe",
        category: "Mr. Krabs",
        image: "assets/images/Cashsafe.jpg",
        description: "The best place to keep money",
        price: 200,
    },

    {
        id:14,
        name: "Mr.Krabs Hat",
        category: "Mr. Krabs",
        image: "assets/images/krabs-hat.jpg",
        description: "Official Captain's Hat of the Al-Hamour Seabed Administration",
        price: 80,
    },

    {
        id:15,
        name: "Money Bag",
        category: "Mr. Krabs",
        image: "assets/images/money-bag.jpg",
        description: "A bag full of delicious cash",
        price: 400,
    },

      {
        id:16,
        name: "Dollar Bill",
        category: "Mr. Krabs",
        image:"assets/images/DollarBill.jpg",
        description: "The first dollar ever earned",
        price:5,
    },

    {
    id: 17,
    name: "Manager Badge",
    category: "Mr. Krabs",
    image: "assets/images/Manager Badge.jpg",
    description: "Show everyone who's boss",
    price: 30,
    },

    {
    id: 18,
    name: "Fancy Anchor Chair",
    category: "Mr. Krabs",
    image: "assets/images/Office Chair.jpg",
    description: "An office chair made for a crab",
    price: 180,
    },

    {
        id:19,
        name: "Clarinet",
        category: "Squidward",
        image: "assets/images/clarinet.jpg",
        description: "A musical instrument for playing the most beautiful melodies",
        price: 180,
    },

    {
        id:20,
        name: "Fine art oil painting",
        category: "Squidward",
        image: "assets/images/painting.jpg",
        description: "A painting from Squidward's unique artistic creations",
        price: 100,
    },

    {
        id:21,
        name: "Lounge Chair",
        category: "Squidward",
        image: "assets/images/lounge-chair.jpg",
        description: "To sit quietly, away from the noise of SpongeBob and Patrick",
        price: 150,
    },

      {
        id:22,
        name: "Artistic Beret",
        category: "Squidward",
        image:"assets/images/beret.jpg",
        description: "Essential for every artist",
        price:30,
    },

    {
    id:23,
    name: "Self Portrait",
    category: "Squidward",
    image: "assets/images/self.jpg",
    description: "A masterpiece of art",
    price: 350,
    },

    {
    id:24,
    name: "Masterpiece Paintbrush",
    category: "Squidward",
    image: "assets/images/paintbrush.jpg",
    description: "For painting those 'abstract' portraits that only true artists understand",
    price: 80,
    },

    {
    id: 25,
    name: "Arpon",
    category: "SpongeBob",
    image: "assets/images/Arpon.jpg",
    description: "A reliable arpon for catching things",
    price: 45,
    },
    {
    id: 26,
    name: "Cozy Blanket",
    category: "Patrick",
    image: "assets/images/Blanket.jpg",
    description: "Patrick's favorite cozy blanket",
    price: 25,
    },
    {
    id: 27,
    name: "Calculator",
    category: "Mr. Krabs",
    image: "assets/images/Calculator.jpg",
    description: "For counting all the money",
    price: 15,
    },
    {
    id: 28,
    name: "Sweet Candy",
    category: "Patrick",
    image: "assets/images/Candy.jpg",
    description: "Delicious underwater candy",
    price: 5,
    },
    {
    id: 29,
    name: "Art Canvas",
    category: "Squidward",
    image: "assets/images/Canvas.jpg",
    description: "Blank canvas for the next masterpiece",
    price: 40,
    },
    {
    id: 30,
    name: "Shiny Coins",
    category: "Mr. Krabs",
    image: "assets/images/Coins.jpg",
    description: "Real shiny coins!",
    price: 100,
    },
    {
    id: 31,
    name: "Frying Pan",
    category: "SpongeBob",
    image: "assets/images/Frying pan.jpg",
    description: "Essential for making the best burgers",
    price: 35,
    },
    {
    id: 32,
    name: "Protective Gloves",
    category: "SpongeBob",
    image: "assets/images/Gloves.jpg",
    description: "Safety first when cooking",
    price: 12,
    },
    {
    id: 33,
    name: "Money Mattress",
    category: "Mr. Krabs",
    image: "assets/images/Money Mattress.jpg",
    description: "Sleep comfortably on your savings",
    price: 800,
    },
    {
    id: 34,
    name: "Notebook",
    category: "Squidward",
    image: "assets/images/Notebook.jpg",
    description: "For writing musical notes",
    price: 8,
    },
    {
    id: 35,
    name: "Piggy Bank",
    category: "Mr. Krabs",
    image: "assets/images/Piggy.jpg",
    description: "Start saving early",
    price: 20,
    },
    {
    id: 36,
    name: "Soft Pillow",
    category: "Patrick",
    image: "assets/images/Pillow.jpg",
    description: "For those long afternoon naps",
    price: 18,
    },
    {
    id: 37,
    name: "Star Lamp",
    category: "Patrick",
    image: "assets/images/Star lamp.jpg",
    description: "Light up your rock",
    price: 22,
    },
    {
    id: 38,
    name: "Teddy Bear",
    category: "SpongeBob",
    image: "assets/images/Teddy.jpg",
    description: "A cuddly friend",
    price: 15,
    },
    {
    id: 39,
    name: "Leather Wallet",
    category: "Mr. Krabs",
    image: "assets/images/Wallet.jpg",
    description: "Keep your cash secure",
    price: 45,
    },
    {
    id: 40,
    name: "Golden Treasure",
    category: "Mr. Krabs",
    image: "assets/images/treasure.jpg",
    description: "The ultimate find",
    price: 1000,
    },
]